// Generated by ts-to-zod
import { z } from "zod";

export const deliveryTypeSchema = z.union([
	z.literal("shipment"),
	z.literal("subscription"),
	z.literal("giftcard"),
]);

export const productTypeSchema = z.union([
	z.literal("standard"),
	z.literal("digital"),
	z.literal("bundle"),
	z.literal("giftcard"),
]);

const attributesSchema = z.record(z.unknown());

export const categorySchema = z.object({
	parent_id: z.string(),
	product_id: z.string(),
	date_created: z.string().optional(),
	date_updated: z.string().optional(),
	id: z.string(),
	sort: z.number().optional(),
});

export const billingScheduleSchema = z.object({
	interval_count: z.number().optional().nullable(),
	interval: z.string().optional().nullable(),
	limit: z.number().optional().nullable(),
	trial_days: z.number().optional().nullable(),
});

export const orderScheduleSchema = z.object({
	interval_count: z.number().optional().nullable(),
	interval: z.string().optional().nullable(),
	limit: z.number().optional().nullable(),
});

export const priceSchema = z.object({
	account_group: z.string().optional().nullable(),
	price: z.number().optional().nullable(),
	quantity_max: z.number().optional().nullable(),
	quantity_min: z.number().optional().nullable(),
});

export const optionInputTypeSchema = z.union([
	z.literal("long_text"),
	z.literal("select"),
	z.literal("short_text"),
	z.literal("toggle"),
]);

export const productOptionValueSchema = z.object({
	id: z.string().optional().nullable(),
	name: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	price: z.number().optional().nullable(),
	shipment_weight: z.number().optional().nullable(),
});

export const crossSellSchema = z.object({
	discount_amount: z.number().optional().nullable(),
	discount_percent: z.number().optional().nullable(),
	discount_type: z.string().optional().nullable(),
	id: z.string().optional().nullable(),
	product_id: z.string().optional().nullable(),
});

export const upSellSchema = z.object({
	id: z.string().optional().nullable(),
	product_id: z.string().optional().nullable(),
});

export const fileSchema = z.object({
	content_type: z.string().optional().nullable(),
	date_uploaded: z.string().optional().nullable(),
	filename: z.string().optional().nullable(),
	height: z.number().optional().nullable(),
	id: z.string().optional().nullable(),
	length: z.number().optional().nullable(),
	md5: z.string().optional().nullable(),
	url: z.string().optional().nullable(),
	width: z.number().optional().nullable(),
});

export const shipmentDimensionsUnitSchema = z.union([
	z.literal("in"),
	z.literal("cm"),
]);

export const shipmentDimensionsSchema = z.object({
	height: z.number().optional().nullable(),
	length: z.number().optional().nullable(),
	unit: shipmentDimensionsUnitSchema.optional().nullable(),
	width: z.number().optional().nullable(),
});

export const categoryIndexSchema = z.object({
	id: z.string().optional().nullable(),
	sort: z.any().optional().nullable(),
});

export const standardPurchaseOptionSchema = z.object({
	active: z.boolean().optional().nullable(),
	price: z.number().optional().nullable(),
	prices: z.array(priceSchema).optional().nullable(),
	sale_price: z.number().optional().nullable(),
	sale: z.boolean().optional().nullable(),
	orig_price: z.number().optional().nullable(),
});

export const subscriptionPlanSchema = z.object({
	active: z.boolean().optional().nullable(),
	billing_schedule: billingScheduleSchema.optional().nullable(),
	description: z.string().optional().nullable(),
	id: z.string().optional().nullable(),
	name: z.string().optional().nullable(),
	order_schedule: orderScheduleSchema.optional().nullable(),
	price: z.number().optional().nullable(),
});

export const productOptionSchema = z.object({
	active: z.boolean().optional().nullable(),
	attribute_id: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	id: z.string().optional().nullable(),
	input_hint: z.string().optional().nullable(),
	input_type: optionInputTypeSchema.optional().nullable(),
	name: z.string().optional().nullable(),
	parent_id: z.string().optional().nullable(),
	price: z.number().optional().nullable(),
	required: z.boolean().optional().nullable(),
	value_id: z.string().optional().nullable(),
	value: z.string().optional().nullable(),
	values: z.array(productOptionValueSchema).optional().nullable(),
	variant: z.boolean().optional().nullable(),
});

export const imageSchema = z.object({
	file: fileSchema.optional().nullable(),
	id: z.string().optional().nullable(),
});

export const subscriptionPurchaseOptionSchema = z.object({
	active: z.boolean().optional().nullable(),
	plans: z.array(subscriptionPlanSchema).optional().nullable(),
});

export const purchaseOptionsSchema = z.object({
	standard: standardPurchaseOptionSchema.optional().nullable(),
	subscription: subscriptionPurchaseOptionSchema.optional().nullable(),
});

export const variantSchema = z.object({
	active: z.boolean().optional().nullable(),
	attributes: attributesSchema.optional().nullable(),
	currency: z.string().optional().nullable(),
	date_created: z.string().optional().nullable(),
	date_updated: z.string().optional().nullable(),
	id: z.string().optional().nullable(),
	name: z.string().optional().nullable(),
	option_value_ids: z.array(z.string()).optional().nullable(),
	parent_id: z.string().optional().nullable(),
	price: z.number().optional().nullable(),
	prices: z.array(priceSchema).optional().nullable(),
	purchase_options: purchaseOptionsSchema.optional().nullable(),
	sale_price: z.number().optional().nullable(),
	orig_price: z.number().optional().nullable(),
	sale: z.boolean().optional().nullable(),
	sku: z.string().optional().nullable(),
});
